---
kind: ConfigMap
apiVersion: v1
metadata:
  name: data-www
data:
  index.html: |
    <html>
      <body>
        <img src="https://http.cat/200"><br/>
        Source <a href="https://http.cat/">http.cat</a>
      </body>
    </html>
